version: "3.9"

services:
  telemetry-api:
    image: interops-telemetry-api:latest
    build: .
    container_name: interop-telemetry-api
    restart: unless-stopped
    ports:
      - "8001:8000"
    networks:
      - interop-net

networks:
  interop-net:
    external: true
